// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  ingredients: dynamic(() => import("./Ingredients")),
  preparation_time: dynamic(() => import("./PreparationTime")),
};
